#!/usr/bin/env python
from MyExecPkg import ExecGit
import sys;
import os;

def print_help():
   print( "help:" )
   print( "\tmy_checkout <feature>\n" )
   print( "<feature> - name of the branch to check out" )

def fetch_all_features():
    #git fetch all commamnd - to identify files to be added
    git_fetch_all_cmd = ["git", "fetch", "-all"]
    retCode,retErr,retStr = execgit.execCommand(git_status_cmd)

def checkout_feature():
    feature = sys.argv[1]
    git_checkout_cmd = ["git", "checkout", feature]
    retCode,retErr,retStr = execgit.execCommand(git_status_cmd)

def main():

    if(len(sys.argv) != 2 ):
        print_help()
        sys.exit(1)

    #initialize objects
    execgit = ExecGit()

    #do work
    fetch_all_feature()
    checkout_feature()

main()
