#!/usr/bin/env python
from MyExecPkg import ExecGit
import sys;
import os;

def print_help():
   print( "help:" )
   print( "\tmy_checkin\n" )
   print( "no arguments" )


def main():

    if(len(sys.argv) > 1 ):
        print_help()
        sys.exit(1)

    #initialize objects
    execgit = ExecGit()

    #git status commamnd - to identify files to be added
    git_status_cmd = ["git", "status", "--porcelain"]
    retCode,retErr,retStr = execgit.execCommand(git_status_cmd)
    listOfFilesAndStatus = retStr.split('\n')
    listOfFilesAndStatus.pop()
    othersList = []
    addModList = []
    for item in listOfFilesAndStatus:
        if( item[0] == "A" or item[0] == "M" or item[0] == "D" or item[0] == "R" or item[0] == "C" ):
             item = item[2:]
             item = item.strip()
             addModList.append(item)
        else:
             item = item[2:]
             item = item.strip()
             othersList.append(item)

    if(len(othersList) > 0):
        print("Error: following files are untracked. Fix them before proceeding" )
        for item in othersList:
            print(item)
    
    listOfPackages = []
    for item in addModList:
        splitPath = item.split(os.path.sep)
        #print(splitPath)
        if( len(splitPath) > 1 ):
            listOfPackages.append(splitPath[0])

    if(len(listOfPackages) == 0 ):
        print("INFO: nothing to check in" )
    else:
        setOfPackages = set(listOfPackages)
        for item in setOfPackages:
            filename = item + os.path.sep + "pkg.version"
            #print(item)
            if( retCode == 0 ):
                #print(retStr)
                fd = open(filename, "r")
                version = fd.read()
                fd.close()
                version = version.strip('\n')
                #print(version)
                versionlist = version.split('-')
                versionlistnum = map(lambda x: int(x), versionlist)
                minorchange = map(lambda x: x, versionlistnum)
                minorchange[2] = minorchange[2] + 1
                majorchange = map(lambda x: x, versionlistnum)
                majorchange[0] = majorchange[0] + 1
                midchange = map(lambda x: x, versionlistnum)
                midchange[1] = midchange[1] + 1
                midchangestr = reduce(lambda x,y: str(x) + "-" + str(y), midchange)
                minorchangestr = reduce(lambda x,y: str(x) + "-" + str(y), minorchange)
                majorchangestr = reduce(lambda x,y: str(x) + "-" + str(y), majorchange)
                print("option 0 " + minorchangestr)
                print("option 1 " + midchangestr)
                print("option 2 " + majorchangestr)
                userValueInt = -1
                while (userValueInt < 0 or userValueInt > 2):
                   userValue = execgit.getUserValue("Enter option (0,1,2):") 
                   userValueInt = int(userValue)
                if( userValueInt == 0 ):
                    versionStr = minorchangestr
                elif( userValueInt == 1):
                    versionStr = midchangestr
                elif(userValueInt == 2 ):
                    versionStr = majorchangestr
                fd = open(filename, "w+")
                fd.write(versionStr)
                fd.close()
                add_pkg_version_cmd = ["git", "add", filename]
                retCode,retErr,retStr = execgit.execCommand(add_pkg_version_cmd)
            else:
                print("Error: " + filename + " not found")
                sys.exit(-1)

main()
