#!/usr/bin/env python
from MyExecPkg import ExecGit
import sys;
import os;

#initialize objects
execgit = ExecGit()

def print_help():
   print( "help:" )
   print( "\tmy_checkout <feature>\n" )
   print( "INFO: <feature> - name of the branch to check out" )

def add_notes():
    #git fetch all commamnd - to identify files to be added
    git_add_notes_cmd = ["git", "notes", "add", "-f", "-m", "checked-in-by-script", "--all"]
    retCode,retErr,retStr = execgit.execCommand(git_add_notes_cmd)

def main():

    if(len(sys.argv) != 1 ):
        print_help()
        sys.exit(1)

    #do work
    add_notes()

main()
